let strip = neopixel.create(DigitalPin.P1, 6, NeoPixelMode.RGB)
strip.setBrightness(255)
basic.forever(function () {
    basic.showIcon(IconNames.Heart)
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Blue))
    strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Orange))
    strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Purple))
    strip.setPixelColor(4, neopixel.colors(NeoPixelColors.Green))
    strip.setPixelColor(5, neopixel.colors(NeoPixelColors.Violet))
    strip.show()
    basic.pause(1000)
    strip.clear()
    strip.show()
    basic.pause(1000)
})
